// SPDX-License-Identifier: MIT
pragma solidity >=0.7.0 <0.9.0;

interface IKnightingRound {
    event Claim(address indexed claimer, uint256 amount);
    event Finalized();
    event GuestlistUpdated(address indexed guestlist);
    event Paused(address account);
    event Sale(
        address indexed buyer,
        uint8 indexed daoId,
        uint256 amountIn,
        uint256 amountOut
    );
    event SaleDurationUpdated(uint256 saleDuration);
    event SaleRecipientUpdated(address indexed recipient);
    event SaleStartUpdated(uint256 saleStart);
    event Sweep(address indexed token, uint256 amount);
    event TokenInLimitUpdated(uint256 tokenInLimit);
    event TokenOutPriceUpdated(uint256 tokenOutPrice);
    event Unpaused(address account);

    function CONTRACT_GOVERNANCE_ROLE() external view returns (bytes32);

    function PAUSER_ROLE() external view returns (bytes32);

    function TECH_OPERATIONS_ROLE() external view returns (bytes32);

    function TREASURY_GOVERNANCE_ROLE() external view returns (bytes32);

    function TREASURY_OPERATIONS_ROLE() external view returns (bytes32);

    function UNPAUSER_ROLE() external view returns (bytes32);

    function __GlobalAccessControlManaged_init(address _globalAccessControl)
        external;

    function boughtAmounts(address) external view returns (uint256);

    function buy(
        uint256 _tokenInAmount,
        uint8 _daoId,
        bytes32[] memory _proof
    ) external returns (uint256 tokenOutAmount_);

    function claim() external returns (uint256 tokenOutAmount_);

    function daoCommitments(uint8) external view returns (uint256);

    function daoVotedFor(address) external view returns (uint8);

    function finalize() external;

    function finalized() external view returns (bool);

    function gac() external view returns (address);

    function getAmountOut(uint256 _tokenInAmount)
        external
        view
        returns (uint256 tokenOutAmount_);

    function getTokenInLimitLeft() external view returns (uint256 limitLeft_);

    function guestlist() external view returns (address);

    function hasClaimed(address) external view returns (bool);

    function initialize(
        address _globalAccessControl,
        address _tokenOut,
        address _tokenIn,
        uint256 _saleStart,
        uint256 _saleDuration,
        uint256 _tokenOutPrice,
        address _saleRecipient,
        address _guestlist,
        uint256 _tokenInLimit
    ) external;

    function pause() external;

    function paused() external view returns (bool);

    function saleDuration() external view returns (uint256);

    function saleEnded() external view returns (bool hasEnded_);

    function saleRecipient() external view returns (address);

    function saleStart() external view returns (uint256);

    function setGuestlist(address _guestlist) external;

    function setSaleDuration(uint256 _saleDuration) external;

    function setSaleRecipient(address _saleRecipient) external;

    function setSaleStart(uint256 _saleStart) external;

    function setTokenInLimit(uint256 _tokenInLimit) external;

    function setTokenOutPrice(uint256 _tokenOutPrice) external;

    function sweep(address _token) external;

    function tokenIn() external view returns (address);

    function tokenInLimit() external view returns (uint256);

    function tokenInNormalizationValue() external view returns (uint256);

    function tokenOut() external view returns (address);

    function tokenOutPrice() external view returns (uint256);

    function totalTokenIn() external view returns (uint256);

    function totalTokenOutBought() external view returns (uint256);

    function totalTokenOutClaimed() external view returns (uint256);

    function unpause() external;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"claimer","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Claim","type":"event"},{"anonymous":false,"inputs":[],"name":"Finalized","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"guestlist","type":"address"}],"name":"GuestlistUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Paused","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"buyer","type":"address"},{"indexed":true,"internalType":"uint8","name":"daoId","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"amountIn","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"amountOut","type":"uint256"}],"name":"Sale","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"saleDuration","type":"uint256"}],"name":"SaleDurationUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"recipient","type":"address"}],"name":"SaleRecipientUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"saleStart","type":"uint256"}],"name":"SaleStartUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"token","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Sweep","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"tokenInLimit","type":"uint256"}],"name":"TokenInLimitUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"tokenOutPrice","type":"uint256"}],"name":"TokenOutPriceUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Unpaused","type":"event"},{"inputs":[],"name":"CONTRACT_GOVERNANCE_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"PAUSER_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TECH_OPERATIONS_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TREASURY_GOVERNANCE_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"TREASURY_OPERATIONS_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"UNPAUSER_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_globalAccessControl","type":"address"}],"name":"__GlobalAccessControlManaged_init","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"boughtAmounts","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_tokenInAmount","type":"uint256"},{"internalType":"uint8","name":"_daoId","type":"uint8"},{"internalType":"bytes32[]","name":"_proof","type":"bytes32[]"}],"name":"buy","outputs":[{"internalType":"uint256","name":"tokenOutAmount_","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"claim","outputs":[{"internalType":"uint256","name":"tokenOutAmount_","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint8","name":"","type":"uint8"}],"name":"daoCommitments","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"daoVotedFor","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"finalize","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"finalized","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"gac","outputs":[{"internalType":"contract IGac","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_tokenInAmount","type":"uint256"}],"name":"getAmountOut","outputs":[{"internalType":"uint256","name":"tokenOutAmount_","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getTokenInLimitLeft","outputs":[{"internalType":"uint256","name":"limitLeft_","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"guestlist","outputs":[{"internalType":"contract IBadgerVipGuestlist","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"hasClaimed","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_globalAccessControl","type":"address"},{"internalType":"address","name":"_tokenOut","type":"address"},{"internalType":"address","name":"_tokenIn","type":"address"},{"internalType":"uint256","name":"_saleStart","type":"uint256"},{"internalType":"uint256","name":"_saleDuration","type":"uint256"},{"internalType":"uint256","name":"_tokenOutPrice","type":"uint256"},{"internalType":"address","name":"_saleRecipient","type":"address"},{"internalType":"address","name":"_guestlist","type":"address"},{"internalType":"uint256","name":"_tokenInLimit","type":"uint256"}],"name":"initialize","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"pause","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"paused","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"saleDuration","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"saleEnded","outputs":[{"internalType":"bool","name":"hasEnded_","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"saleRecipient","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"saleStart","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_guestlist","type":"address"}],"name":"setGuestlist","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_saleDuration","type":"uint256"}],"name":"setSaleDuration","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_saleRecipient","type":"address"}],"name":"setSaleRecipient","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_saleStart","type":"uint256"}],"name":"setSaleStart","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_tokenInLimit","type":"uint256"}],"name":"setTokenInLimit","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_tokenOutPrice","type":"uint256"}],"name":"setTokenOutPrice","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_token","type":"address"}],"name":"sweep","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"tokenIn","outputs":[{"internalType":"contract ERC20Upgradeable","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"tokenInLimit","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"tokenInNormalizationValue","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"tokenOut","outputs":[{"internalType":"contract ERC20Upgradeable","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"tokenOutPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalTokenIn","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalTokenOutBought","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalTokenOutClaimed","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"unpause","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/