autofetch_sources: True

networks:
  default: mainnet-fork

dotenv: .env

dependencies:
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0
    - safe-global/safe-contracts@1.3.0

compiler:
    solc:
        remappings:
          - "openzeppelin-contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0/contracts"
          - "@gnosis-safe=safe-global/safe-contracts@1.3.0/contracts"
