// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IFactoryLlama {
    event LlamaPayCreated(address token, address llamaPay);

    function createLlamaPayContract(address _token)
        external
        returns (address llamaPayContract);

    function getLlamaPayContractByIndex(uint256)
        external
        view
        returns (address);

    function getLlamaPayContractByToken(address _token)
        external
        view
        returns (address predictedAddress, bool isDeployed);

    function getLlamaPayContractCount() external view returns (uint256);

    function parameter() external view returns (address);
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"token","type":"address"},{"indexed":false,"internalType":"address","name":"llamaPay","type":"address"}],"name":"LlamaPayCreated","type":"event"},{"inputs":[{"internalType":"address","name":"_token","type":"address"}],"name":"createLlamaPayContract","outputs":[{"internalType":"address","name":"llamaPayContract","type":"address"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"getLlamaPayContractByIndex","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_token","type":"address"}],"name":"getLlamaPayContractByToken","outputs":[{"internalType":"address","name":"predictedAddress","type":"address"},{"internalType":"bool","name":"isDeployed","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getLlamaPayContractCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"parameter","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}]
*/